# Generated by Django 4.2.4 on 2023-08-20 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.CharField(max_length=100, verbose_name='Имя ссылки')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='shop/', verbose_name='Изображение')),
                ('views', models.IntegerField(verbose_name='Просмотров')),
                ('date_creation', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('publication', models.BooleanField(verbose_name='Опубликован')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'записи блога',
            },
        ),
    ]
