# Generated by Django 4.2.4 on 2023-08-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_blogentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='publication',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
    ]
