# Generated by Django 4.2.4 on 2023-08-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_blogentry_publication_alter_blogentry_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='slug',
            field=models.CharField(max_length=100, verbose_name='slug'),
        ),
    ]
